ros__parameters:
  axis_angular:
    pitch: 4
    roll: 3
    yaw: 5
  axis_linear:
    x: 0
    y: 1
    z: 2
  enable_button: -1
  enable_turbo_button: -1
  frame: world_link
  require_enable_button: false
  scale_angular:
    pitch: 0.05
    roll: -0.05
    yaw: 0.05
  scale_angular_turbo:
    pitch: 0.7
    roll: -0.7
    yaw: 1.0
  scale_linear:
    x: -0.05
    y: 0.05
    z: 0.05
  scale_linear_turbo:
    x: -0.2
    y: 0.2
    z: 0.2
