ros__parameters:
  axis_angular:
    pitch: 4
    roll: 5
    yaw: 3
  axis_linear:
    x: 2
    y: 1
    z: 0
  enable_button: -1
  enable_turbo_button: -1
  frame: neura_1/flange
  require_enable_button: false
  scale_angular:
    pitch: 0.2
    roll: -0.2
    yaw: -0.2
  scale_angular_turbo:
    pitch: 0.7
    roll: -0.7
    yaw: -1.0
  scale_linear:
    x: -0.2
    y: 0.2
    z: -0.2
  scale_linear_turbo:
    x: -0.7
    y: 0.7
    z: -0.7
