ros__parameters:
  axis_angular:
    pitch: 4
    roll: 3
    yaw: 5
  axis_linear:
    x: 0
    y: 1
    z: 2
  enable_button: 1
  enable_turbo_button: 0
  frame: neura_2/world
  require_enable_button: true
  scale_angular:
    pitch: -0.1
    roll: 0.1
    yaw: 0.1
  scale_angular_turbo:
    pitch: -0.3
    roll: 0.3
    yaw: 0.3
  scale_linear:
    x: 0.1
    y: -0.1
    z: 0.1
  scale_linear_turbo:
    x: 0.3
    y: -0.3
    z: 0.3
