ros__parameters:
  axis_angular:
    pitch: 4
    roll: 3
    yaw: 5
  axis_linear:
    x: 0
    y: 1
    z: 2
  enable_button: 1
  enable_turbo_button: 0
  frame: neura_2/flange
  require_enable_button: true
  scale_angular:
    pitch: -0.1
    roll: 0.1
    yaw: 0.1
  scale_angular_turbo:
    pitch: -0.5
    roll: 0.5
    yaw: 0.5
  scale_linear:
    x: 0.1
    y: -0.1
    z: 0.1
  scale_linear_turbo:
    x: 0.5
    y: -0.5
    z: 0.5
