ros__parameters:
  axis_angular:
    pitch: 4
    roll: 3
    yaw: 5
  axis_linear:
    x: 0
    y: 1
    z: 2
  enable_button: 0
  enable_turbo_button: 1
  frame: neura_2/world
  require_enable_button: false
  scale_angular:
    pitch: -1.0
    roll: 1.0
    yaw: 2.0
  scale_angular_turbo:
    pitch: -2.0
    roll: 2.0
    yaw: 4.0
  scale_linear:
    x: 0.5
    y: -0.5
    z: 0.5
  scale_linear_turbo:
    x: 1.5
    y: -1.5
    z: 1.5
