ros__parameters:
  axis_angular:
    pitch: 0
    roll: 1
    yaw: 2
  axis_linear:
    x: 4
    y: 3
    z: 5
  enable_button: 1
  enable_turbo_button: 0
  frame: neura_2/maira7M_link0
  require_enable_button: true
  scale_angular:
    pitch: 0
    roll: 0
    yaw: 0
  scale_angular_turbo:
    pitch: 0
    roll: 0
    yaw: 0
  scale_linear:
    x: -0.02
    y: -0.02
    z: -0.02
  scale_linear_turbo:
    x: -0.1
    y: -0.1
    z: -0.1
